DELETE FROM CostConverter
DELETE FROM Country
DELETE FROM Groups
DELETE FROM Product
DELETE FROM Product_count
DELETE FROM Products_Recipes
DELETE FROM Recipe
DELETE FROM RecipeViewed
DELETE FROM Season
DELETE FROM Users
DELETE FROM ViewedBy

DBCC CHECKIDENT ('CostConverter', RESEED, 0);
DBCC CHECKIDENT ('Country', RESEED, 0);
DBCC CHECKIDENT ('Groups', RESEED, 0);
DBCC CHECKIDENT ('Product', RESEED, 0);
DBCC CHECKIDENT ('Product_count', RESEED, 0);
DBCC CHECKIDENT ('Products_Recipes', RESEED, 0);
DBCC CHECKIDENT ('Recipe', RESEED, 0);
DBCC CHECKIDENT ('RecipeViewed', RESEED, 0);
DBCC CHECKIDENT ('Season', RESEED, 0);
DBCC CHECKIDENT ('ViewedBy', RESEED, 0);